### Feature one
POST http://localhost:3000/api/v1/feature/create
Content-Type: application/json

{
  "name": "Feature One",
  "description": "Some desc",
  "projectKey": "mpo1"
}

### Feature two
POST http://localhost:3000/api/v1/feature/create
Content-Type: application/json

{
  "name": "Feature Two",
  "description": "Some desc",
  "projectKey": "mpt1"
}

### Feature three
POST http://localhost:3000/api/v1/feature/create
Content-Type: application/json

{
  "name": "Feature Three",
  "description": "Some desc",
  "projectKey": "mpt2"
}

### Feature four
POST http://localhost:3000/api/v1/feature/create
Content-Type: application/json

{
  "name": "Feature Four",
  "description": "Some desc",
  "projectKey": "mpf1"
}

### Feature five
POST http://localhost:3000/api/v1/feature/create
Content-Type: application/json

{
  "name": "Feature Five",
  "description": "Some desc",
  "projectKey": "mpo1"
}